SELECT
    pat.PAT_EPI_ID,
    pat.PAT_MRN_ID,
    pat.PAT_FULL_NM,
    op.ORD_PROC_DESC,
    op.ORD_PROC_DTTM,
    op.ORD_PROC_STS_DESC,
    rpt.LAB_COMP_NM,
    rpt.MULT_LN_VAL_STORAGE AS PATHOLOGY_REPORT_TEXT,
    rpt.LAST_UPDATE_DTTM
FROM
    EDA_SILVER_EDV_PRD.EDV_EPIC.M_PATHOLOGY_REPORTS_V rpt
    JOIN EDA_SILVER_EDV_PRD.EDV_EPIC.S_RES_DB_MAIN res ON rpt.K_RESULT_KEY = res.K_RESULT_KEY
    JOIN EDA_SILVER_EDV_PRD.EDV_EPIC.HR_ORD_PROC_PRIMARY hr on res.K_RES_ORD_KEY = hr.K_ORD_KEY
    JOIN EDA_SILVER_EDV_PRD.EDV_EPIC.BK_ORD_PROC op ON hr.K_ORD_KEY = op.K_ORD_KEY
    JOIN EDA_SILVER_EDV_PRD.EDV_EPIC.BK_PATIENT pat ON hr.K_PAT_KEY = pat.K_PAT_KEY
WHERE
    rpt.FULLY_CONCATENATED_REPORT = 1
ORDER BY
    op.ORD_PROC_DTTM DESC;